name: docman_example
description: Demonstrates how to use the docman plugin.
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  docman:
    path: ../


dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/pdf/
    - assets/images/
    - assets/video/
  uses-material-design: true