name: docman
description: Flutter File & Directory Plugin. Easy Android file operations with Storage Access Framework (SAF) API integration.
repository: https://github.com/devdfcom/docman
issue_tracker: https://github.com/devdfcom/docman/issues
version: 1.0.1

environment:
  sdk: ^3.5.2
  flutter: '>=3.3.0'

flutter:
  plugin:
    platforms:
      android:
        package: devdf.plugins.docman
        pluginClass: DocManPlugin

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

topics:
  - saf
  - files
  - picker
  - file-selection
  - storage

screenshots:
  - description: The docman logo.
    path: example/assets/images/jpeg_example.jpg

funding:
  - https://github.com/sponsors/devdfcom
  - https://ko-fi.com/devdf
