name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # tag-pattern on pub.dev: 'v{{1.0.0}}'

# Publish using custom workflow
jobs:
  publish:
    name: Publish
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
      # Make sure the stable version of Flutter is available
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
          cache: true
      # Download all Flutter packages
      - name: Download dependencies
        run: flutter pub get
      # Publish the package
      - name: Publish package
        run: dart pub publish -v -f
