name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # tag-pattern on pub.dev: 'v{{1.0.0}}'

permissions:
  id-token: write
  contents: write
  pull-requests: write

# Publish using custom workflow
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          environment: pub.dev
      - name: Publish
        run: dart pub publish
